// Server error codes (the `error` message and create/join failures) as
// Modern Standard Arabic text.
const _errors = {
  'notYourTurn': 'ليس دورك',
  'badBid': 'طلب غير صالح',
  'mustFollowSuit': 'يجب أن تتبع الشكل المطلوب',
  'notInHand': 'هذه الورقة ليست معك',
  'wrongPhase': 'ليس هذا وقتها',
  'seatTaken': 'المقعد محجوز',
  'gameStarted': 'بدأت اللعبة في هذه الغرفة',
  'roomFull': 'اكتملت الغرفة',
  'badName': 'اكتب اسمك',
  'notFound': 'لم نجد غرفة بهذا الرمز',
  'network': 'تعذّر الاتصال بخادم اللعبة',
  'gameFull': 'الطاولة ممتلئة',
  'kicked': 'أخرجك صاحب الغرفة من الطاولة',
  'notOwner': 'هذا لصاحب الغرفة فقط',
  'kickDisabled': 'إخراج اللاعبين غير مفعّل في هذه اللعبة',
  'badSettings': 'إعدادات غير صالحة',
  'chatOff': 'الدردشة مغلقة في هذه اللعبة',
  'chatTooFast': 'تمهّل، أرسلت رسائل كثيرة',
  'badChat': 'الرسالة طويلة أو فارغة',
  'badContract': 'طلبة غير صالحة',
  'contractUsed': 'لُعبت هذه الطلبة في هذه المملكة',
  'badDouble': 'لا يمكنك تدبيل هذه الورقة',
  'cannotPlace': 'لا يمكن وضع هذه الورقة الآن',
  'noPlayers': 'لا يوجد لاعبون',
  'badCall': 'لا يمكنك هذا الطلب الآن',
  'badSuit': 'لا يمكنك اختيار هذا النوع',
  'badRaise': 'مضاعفة غير صالحة',
  'badDraw': 'سحب غير صالح',
  'fireEmpty': 'لا توجد ورقة في النار',
  'badMeld': 'هذه ليست مجموعة صحيحة',
  'openTooLow': 'مجموع نزولك الأول أقل من المطلوب',
  'mustUseFire': 'يجب أن تنزّل ورقة النار التي أخذتها',
  'notOpened': 'انزل مجموعاتك أولًا قبل التركيب',
  'cannotLayoff': 'لا تركب هذه الورقة على هذه المجموعة',
  'closedTrump': 'اللعب مغلق: لا تبدأ بورقة حكم ومعك نوع آخر',
  // the account and the API (apps/server/src)
  'signedOut': 'انتهت جلستك، سجّل دخولك من جديد',
  'banned': 'هذا الحساب موقوف',
  'noUnits': 'رصيد الوحدات لا يكفي',
  'noStars': 'رصيد النجوم لا يكفي',
  'offerGone': 'انتهى هذا العرض',
  'badAmount': 'قيمة غير صالحة',
  'badItem': 'هذا العنصر غير موجود',
  'owned': 'تملك هذا العنصر بالفعل',
  'vipOnly': 'هذه للأعضاء الذهبيين فقط',
  'notOwned': 'لا تملك هذا العنصر',
  'giftTaken': 'أخذت هدية اليوم، عُد غداً',
  'renameTooSoon': 'يمكنك تغيير اسمك مرة واحدة في اليوم',
  'badCountry': 'دولة غير صالحة',
  'badUser': 'لم نجد هذا اللاعب',
  'badToken': 'تعذّر التحقق، حاول مرة أخرى',
  'badChallenge': 'تحدٍّ غير موجود',
  'notDone': 'لم تُنجز هذا التحدي بعد',
  'claimed': 'استلمت جائزة هذا التحدي',
  'blocked': 'لا يمكن التواصل مع هذا اللاعب',
  'messagesOff': 'هذا اللاعب لا يستقبل الرسائل',
  'badText': 'اكتب نصاً واضحاً',
  'tooFast': 'تمهّل قليلاً ثم حاول',
  'tooMany': 'محاولات كثيرة، حاول لاحقاً',
  'badReason': 'اختر سبب البلاغ',
  'badProduct': 'منتج غير معروف',
  'badPlatform': 'متجر غير معروف',
  'purchaseUsed': 'استُخدم هذا الشراء من قبل',
  'paymentsOff': 'الدفع غير متاح حالياً، حاول لاحقاً',
  'badPurchase': 'لم يتم التحقق من عملية الشراء',
  'purchasePending': 'عملية الشراء قيد المعالجة، ستصلك عند اكتمالها',
  'storeUnreachable': 'تعذّر التحقق من المتجر الآن، سنعيد المحاولة',
  'lowLevel': 'مستواك أقل من المطلوب',
  'notAllowed': 'لا تملك صلاحية لهذا',
  'clubPending': 'النادي بانتظار موافقة فريق سمرة',
  'badClub': 'لم نجد هذا النادي',
  'mustAgree': 'يجب الموافقة على القوانين أولاً',
  'inClub': 'أنت عضو في نادٍ، اخرج منه أولاً',
  'nameShort': 'الاسم قصير جداً',
  'nameTaken': 'هذا الاسم مستخدم',
  'badType': 'اختر النوع',
  'badEmblem': 'اختر شعاراً',
  'badColor': 'اختر لوناً',
  'badLevel': 'مستوى غير صالح',
  'clubFull': 'النادي ممتلئ',
  'inviteOnly': 'هذا النادي بالدعوة فقط',
  'requested': 'أرسلت طلباً بالفعل',
  'tooManyRequests': 'طلبات كثيرة على هذا النادي، حاول لاحقاً',
  'inOtherClub': 'هذا اللاعب في نادٍ آخر',
  'alreadyMember': 'هذا اللاعب عضو بالفعل',
  'alreadyInvited': 'دعوته من قبل',
  'tooManyModerators': 'وصلت إلى الحد الأقصى من المشرفين',
  'notMember': 'هذا لأعضاء النادي فقط',
  'compBanned': 'حسابك ممنوع من المسابقات',
  'tooManyOpen': 'لديك مسابقات مفتوحة كثيرة، انتظر انتهاء إحداها',
  'badGame': 'لعبة غير متاحة في المسابقات',
  'badSeats': 'عدد مقاعد غير صالح لهذه اللعبة',
  'badFee': 'رسوم غير صالحة',
  'badPrize': 'جائزة غير صالحة',
  'badTime': 'مدة تسجيل غير صالحة',
  'badTarget': 'نتيجة نهائية غير صالحة',
  'closed': 'التسجيل مغلق',
  'alreadyIn': 'أنت مسجّل بالفعل',
  'full': 'المقاعد ممتلئة',
  'barred': 'لا يمكنك دخول مسابقات هذا المنظم',
  'badPartner': 'اكتب رقم شريكك',
  'partnerIn': 'شريكك مسجّل بالفعل',
  'partnerBarred': 'شريكك لا يستطيع دخول هذه المسابقة',
  'started': 'بدأت المسابقة',
  'notIn': 'لست مشتركاً في هذه المسابقة',
  'notOrganiser': 'هذا للمنظم فقط',
  'badEntry': 'لم نجد هذا المشترك',
  'notEnough': 'لم يكتمل 75% من المقاعد بعد',
  'reviewOver': 'انتهت فترة الشكاوى',
  'shortComplaint': 'اشرح الشكوى بجملة واضحة (أربع كلمات على الأقل)',
  'notFrozen': 'المسابقة ليست مجمّدة',
  'badCompetition': 'لم نجد هذه المسابقة',
  'googleOff': 'الدخول بحساب Google غير متاح حالياً',
  'googleTaken': 'حساب Google هذا مربوط بحساب آخر',
  'appleTaken': 'حساب Apple هذا مربوط بحساب آخر',
  'server': 'حدث خطأ في الخادم، حاول لاحقاً',
  'badGift': 'لا يمكن إرسال هذه الهدية',
  'giftsOff': 'هذا اللاعب لا يستقبل الهدايا',
  'notInMatch': 'هذه الطاولة ليست لك',
  'tooLate': 'تأخرت عن مباراتك فلعب الكمبيوتر مكانك',
  'badMatch': 'هذه المباراة لم تعد موجودة',
  'noRematch': 'لا يمكن إعادة هذه اللعبة',
  'playersMissing': 'بعض اللاعبين غادروا',
};

/// Arabic text for a server error code or a connection exception.
String errorText(Object error) {
  final s = error.toString();
  if (_errors.containsKey(s)) return _errors[s]!;
  // a match-maker refusal carries the code in its message, e.g. "lowLevel"; look for whole words only
  for (final word in s.split(RegExp(r'[^A-Za-z]+'))) {
    if (_errors.containsKey(word)) return _errors[word]!;
  }
  for (final e in _errors.entries) {
    if (s.contains(e.key)) return e.value;
  }
  if (s.contains('Connection') || s.contains('Socket') || s.contains('refused')) return _errors['network']!;
  return 'حدث خطأ، حاول مرة أخرى';
}
